version: '3.9'

services:
  app:
    container_name: nlwspacetime
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    
    volumes:
      - .:/app/api/
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    depends_on:
      - db
  db:
    container_name: nlw-db
    image: postgres:14.1-alpine
    restart: always
    tty: true
    volumes:
      # - .docker/.pgdata:/var/lib/postgresql/data
      - ./database/migrations/01_create_tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=nlwspacetime
    ports:
      - '5432:5432'
